<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTmybwmt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTmybwmt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTmybwmt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTmybwmt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTmybwmt\appProdProjectContainer([
    'container.build_hash' => 'Tmybwmt',
    'container.build_id' => 'c1e31c64',
    'container.build_time' => 1605621796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTmybwmt');
