<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqnrdfh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqnrdfh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSqnrdfh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSqnrdfh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSqnrdfh\appProdProjectContainer([
    'container.build_hash' => 'Sqnrdfh',
    'container.build_id' => '44b74a36',
    'container.build_time' => 1608032483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqnrdfh');
