<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfxlzlu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfxlzlu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLfxlzlu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLfxlzlu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLfxlzlu\appProdProjectContainer([
    'container.build_hash' => 'Lfxlzlu',
    'container.build_id' => 'eb405ade',
    'container.build_time' => 1606253947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfxlzlu');
